services:
  react_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: react_app
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.reactapp.rule=Host(`${APP_DOMAIN:-yourdomain.com}`)"
      - "traefik.http.routers.reactapp.entrypoints=websecure"
      - "traefik.http.routers.reactapp.tls.certresolver=${CERT_RESOLVER:-letsencrypt}"
      - "traefik.http.services.reactapp.loadbalancer.server.port=80"

      